<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<%
String result=(request.getParameter("amount"));
String name=(String)request.getAttribute("cname");
out.println("Total Amount generated by "+name+" is "+ result);
%>
<br><a href="home.jsp"><button>GoToHomePage</button></a>
</body>
</html>